GCC?=gcc
build: traveling_salesman_openmp.c
	@echo "Building traveling_salesman_openmp.c"
	@${GCC} -fopenmp -o tsp_openmp traveling_salesman_openmp.c 
	@echo "Done building traveling_salesman_openmp.c"